version: "3.9"

services:
  currency-exchange:
    image: foxcatcher2426/spring-microservices-currency-exchange-service:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8000:8000"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  currency-conversion:
    image: foxcatcher2426/spring-microservices-currency-conversion-microservice:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8100:8100"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  api-gateway:
    image: foxcatcher2426/spring-microservices-api-gateway:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          memory: 700m
    ports:
      - "8765:8765"
    networks:
      - currency-network
    depends_on:
      - naming-server
      - rabbitmq
    environment:
      EUREKA.CLIENT.SERVICE-URL.DEFAULTZONE: http://naming-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit

  naming-server:
      image: foxcatcher2426/spring-microservices-naming-server:0.0.1-SNAPSHOT
      deploy:
        resources:
          limits:
            memory: 700m
      ports:
        - "8761:8761"
      networks:
        - currency-network

  #docker run -p 9411:9411 openzipkin/zipkin:2.23
  zipkin-server:
    image: openzipkin/zipkin:2.23
    deploy:
      resources:
        limits:
          memory: 300m
    ports:
      - "9411:9411"
    networks:
      - currency-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: always

  #docker run -it --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.9-management
  rabbitmq:
      image: rabbitmq:3.9-management
      deploy:
        resources:
          limits:
            memory: 300m
      ports:
        - "5672:5672"
        - "15672:15672"
      networks:
        - currency-network

networks:
  currency-network:


